spring:
  application:
    name: demoproject
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
server:
  servlet:
    encoding:
      force-response: true  # mustache 한글깨짐수정